server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/consultorio_db
    username: consultorio
    password: consultorio123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Cambiar a 'validate' o 'none' en producción
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://mongo:27017/consultorio_cache

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
